version: '3.8'
services:
  zookeeper:
    container_name: zookeeper-container
    image: bitnami/zookeeper:latest
    expose:
      - '2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    container_name: kafka-container
    image: bitnami/kafka:latest
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  mongodb:
    container_name: mongodb-container
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=logdb
    ports:
      - '27017:27017'
    volumes:
      - mongodb-volume:/data/db
      - mongodb-volume:/data/configdb
  web:
    container_name: web-container
    image: braintr/kartaca-internship-task
    build: .
    command: node web/app.js
    volumes:
      - app-volume:/app
    ports:
      - '80:80'
    depends_on:
      - mongodb
  producer:
    container_name: producer-container
    image: braintr/kartaca-internship-task
    command: node producer/producer.js
    volumes:
      - app-volume:/app
    depends_on:
      - kafka
      - web
  consumer:
    container_name: consumer-container
    image: braintr/kartaca-internship-task
    command: node consumer/consumer.js
    volumes:
      - app-volume:/app
    depends_on:
      - kafka
      - mongodb
volumes:
  app-volume:
  mongodb-volume: